version: "3.8"

services:
  pricing-service:
    build: .
    container_name: pricing-service
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: default
    networks:
      - pricing-net
    restart: unless-stopped

networks:
  pricing-net:
    driver: bridge
